In [2]:
import tensorflow as tf

In [3]:
from tensorflow import keras

In [7]:
mnist = keras.datasets.mnist


In [8]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [9]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [10]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [11]:
x_test, x_train = x_test / 255.0, x_train / 255.0

In [15]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


In [16]:
predictions = model(x_train[:1]).numpy()
predictions



If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.2686468 ,  0.47276407,  0.38738397, -0.47164282, -0.92342657,
        -0.30891094, -0.44950128, -0.04151148, -0.09552453,  0.47807845]],
      dtype=float32)

In [17]:
tf.nn.softmax(predictions).numpy()


array([[0.07867175, 0.16512373, 0.15161054, 0.0642183 , 0.04087442,
        0.07556703, 0.06565604, 0.09873303, 0.09354162, 0.1660036 ]],
      dtype=float32)

In [18]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [19]:
loss_fn(y_train[:1], predictions).numpy()


2.5827353

In [20]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [21]:
model.fit(x_train, y_train, epochs=5)


Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 7s 113us/sample - loss: 0.3016 - accuracy: 0.9120
Epoch 2/5
60000/60000 [==============================] - 6s 100us/sample - loss: 0.1459 - accuracy: 0.9567
Epoch 3/5
60000/60000 [==============================] - 7s 117us/sample - loss: 0.1104 - accuracy: 0.9668
Epoch 4/5
60000/60000 [==============================] - 6s 99us/sample - loss: 0.0884 - accuracy: 0.9726
Epoch 5/5
60000/60000 [==============================] - 6s 98us/sample - loss: 0.0756 - accuracy: 0.9760


In [22]:
model.evaluate(x_test,  y_test, verbose=2)


10000/10000 - 1s - loss: 0.0853 - accuracy: 0.9747


[0.0852545530593954, 0.9747]

In [23]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [24]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1154082e-09, 5.4474988e-08, 6.9263388e-07, 4.2120673e-06,
        1.2147386e-12, 8.1181231e-09, 9.9800624e-15, 9.9999499e-01,
        7.1402089e-09, 5.1375594e-08],
       [6.8043677e-09, 1.3222647e-05, 9.9997246e-01, 1.2535473e-05,
        3.5676670e-13, 1.6780812e-07, 6.8246311e-09, 1.2289672e-11,
        1.6690008e-06, 4.1800605e-11],
       [1.1680012e-06, 9.9927038e-01, 1.2502045e-04, 1.8554740e-05,
        7.1941591e-05, 1.6296017e-05, 1.3108630e-04, 2.2984366e-04,
        1.3293428e-04, 2.6810496e-06],
       [9.9953663e-01, 1.4677570e-08, 2.0156831e-04, 3.2349390e-06,
        6.9108876e-07, 5.1699775e-05, 1.6718172e-04, 3.5928759e-05,
        9.4268410e-07, 2.0019049e-06],
       [1.3050243e-06, 1.9851136e-08, 1.1239996e-06, 1.1009457e-09,
        9.9941826e-01, 2.6484241e-07, 8.6229943e-07, 4.4253553e-05,
        1.1838748e-07, 5.3391815e-04]], dtype=float32)>